apiVersion: v1 
kind: Pod
metadeta:
  name: multi-container
  labels:
    project: roboshop
    purpose: mutlti-container-demo
spec:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
