apiVersion: v1
kind: Secret
metadata:
  name: pod-secret
  labels:
    purpose: secret
    env: dev
type: Opaque
data:
  username: "YWRtaW4=" #in bash use command for username: echo -n "admin" | base64
  password: "YWRtaW4zMjE=" #in bash use command for password: echo -n "admin321" | base64